camera_node:
  ros__parameters:
    color_image_topic: "/head_front_camera/rgb/image_raw"
    depth_image_topic: "/head_front_camera/depth_registered/image_raw"
    camera_info_topic: "/head_front_camera/rgb/camera_info"
    frames_approx_sync: false

    post_processing:
      package: "skeleton_tracking"
      module: "skeleton_post_processing"
      class: "SkeletonDetection"

    skeleton_detection_node:
      roi_half_size: 1
      debug_topic: True


skeleton_filter_node:
  ros__parameters:
    q_noise: [0.01, 0.01, 0.01, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1]
    r_noise: [0.05, 0.05, 0.1]
