name: humble

on:
  pull_request:
    branches:
      - ros2_wip
  push:
    branches:
      - ros2_wip
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false

    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.0
        with:
          required-ros-distributions: humble

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install python dep
        run: |
          python3 -m pip install -r requirements.txt

      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: skeleton_tracking
          target-ros2-distro: humble
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          vcs-repo-file-url: https://raw.githubusercontent.com/SamueleSandrini/skeleton_trajectory/refs/heads/ros2_wip/dependencies.repos

#      - name: Run Tests
#        run: |
#          cd ros_ws
#          source /opt/ros/humble/setup.sh 
#          source install/setup.bash 
#          pytest-3 --cov=skeleton_tracking --cov-report=term-missing --cov-report=xml:coverage.xml

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1.2.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ros_ws/coverage.xml 
      #     flags: unittests
      #     name: codecov-umbrella
